default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: maestro_tracker_development

test:
  <<: *default
  database: maestro_tracker_test

production:
  <<: *default
  database: maestro_tracker
